### PR TITLE
fix: use default fetch mode for PHP8 PDO implementation

### PR DESCRIPTION
**Pull request by Kenneth-Sills**
This is a copy of the changes from #15 (0e864b2), making the two versions of `FakePdo` behave the same WRT respecting `->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, *)`.

Made sure to add an appropriate test.

### CODE REVIEW

**Review by MelechMizrachi — APPROVED** [review]

**Comment by MelechMizrachi** [comment]
Just need to fix the conflict since I merged #46 first.

**Comment by Kenneth-Sills** [comment]
@MelechMizrachi Of course, thanks for such a quick turnaround time! The conflict is resolved. 😄

**Review by MelechMizrachi — APPROVED** [review]

**Comment by MelechMizrachi** [comment]
Absolutely, @Kenneth-Sills! Thanks again for the contribution :)

**Comment by MelechMizrachi** [comment]
Added in release https://github.com/vimeo/php-mysql-engine/releases/tag/0.7.3

**Pull request merged**
