### PR TITLE
Add missing #[\ReturnTypeWillChange] for PHP 8.1 support

### PR DESCRIPTION
**Pull request by zonuexe**
refs https://github.com/vimeo/php-mysql-engine/pull/33

### CODE REVIEW

**Comment by zonuexe** [comment]
@muglug Could you please review this PR?

**Comment by zonuexe** [comment]
@cfebs Hi, can this PR be merged?

**Review by MelechMizrachi — APPROVED** [review]
We should probably use the proper typehints in the future.

**Comment by sergiosalvatore** [comment]
Thanks @zonuexe for the contribution and @MelechMizrachi for the merge.

**Comment by zonuexe** [comment]
I love php-mysql-engine so I'm relieved it's released!

**Pull request merged**
